name: react_async_example
description: An example project
version: 0.1.0
environment:
  sdk: '>=2.0.0 <3.0.0' 
dependencies:
  react: ^4.5.0
  react_async:
    path: ../
dev_dependencies:
  build_runner: ">=0.8.10 <2.0.0" 
  build_web_compilers: ">=0.3.6 <0.5.0"